# Generated by Django 5.1.1 on 2025-11-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list_type', models.CharField(choices=[('watched', 'İzledim'), ('watchlist', 'İzlenecek'), ('read', 'Okudum'), ('readlist', 'Okunacak'), ('custom', 'Özel Liste')], default='custom', max_length=20)),
                ('books', models.ManyToManyField(blank=True, related_name='lists', to='core.book')),
                ('movies', models.ManyToManyField(blank=True, related_name='lists', to='core.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
