# Generated by Django 5.1.1 on 2025-11-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userlist'),
        ),
    ]
