# Generated by Django 5.1.1 on 2025-11-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitycomment_activitylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='original_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('RATED', 'Puanladı'), ('REVIEWED', 'Yorumladı'), ('ADDED_LIST', 'Listeye Ekledi'), ('SHARED', 'Paylaştı')], max_length=20),
        ),
    ]
