# Generated by Django 5.1.1 on 2025-11-29 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity_original_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_reference', to='core.activitycomment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('RATED', 'Puanladı'), ('REVIEWED', 'Yorumladı'), ('ADDED_LIST', 'Listeye Ekledi'), ('SHARED', 'Paylaştı'), ('COMMENTED', 'Yorum Yaptı')], max_length=20),
        ),
    ]
