# Generated by Django 5.1.1 on 2025-12-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book'), ('user', 'movie')},
        ),
        migrations.AddField(
            model_name='activity',
            name='tv_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tvseries'),
        ),
        migrations.AddField(
            model_name='rating',
            name='tv_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tvseries'),
        ),
        migrations.AddField(
            model_name='review',
            name='tv_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tvseries'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='tv_series',
            field=models.ManyToManyField(blank=True, related_name='lists', to='core.tvseries'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book'), ('user', 'movie'), ('user', 'tv_series')},
        ),
    ]
