# Generated by Django 5.1.1 on 2025-12-04 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tvseries_alter_rating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
